# 🧪 Week 1 - Lab Task: Working with DataFrames and Arrays #

**🎯 Objective**

Explore and manipulate data by using Pandas and NumPy.

### Dataset ###
Use the Titanic dataset, available from the official Pandas documentation repository.

🔗 Dataset URL:
https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv

📥 Instruction:
Load the dataset directly into a DataFrame from the URL:

In [141]:
import pandas as pd
import numpy as np

df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")

### Part 1: Data Exploration ###
1. Print the shape and column names of the dataset.

2. Display basic information and summary statistics about the dataset.

3. Show the first 10 rows.

In [142]:
#1. Print the shape and column names of the dataset.
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

Shape: (891, 12)
Columns: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

In [143]:
#2. Display basic information and summary statistics about the dataset.
df.info()
display(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [144]:
#3. Show the first 10 rows.
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

### Part 2: Indexing and Selection ###
1. Select the names column.

2. Select multiple columns of your choice.

3. Select a single row from the dataset.

4. Select a rectangular section (subset of rows and columns).

**Notes**

Step 3

- the selected row is the first row

Step 4
- the rectangular section was the first 5 rows and the columns name, sex, age

In [ ]:
# 1. Select the names column.
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                  Heikkinen, Miss Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                          Graham, Miss Margaret Edith
888              Johnston, Miss Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
# 2. Select multiple columns of your choice.
df[['Name','Sex','Age']]

                                                  Name     Sex   Age
0                              Braund, Mr. Owen Harris    male  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                                Heikkinen, Miss Laina  female  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                             Allen, Mr. William Henry    male  35.0
..                                                 ...     ...   ...
886                              Montvila, Rev. Juozas    male  27.0
887                        Graham, Miss Margaret Edith  female  19.0
888            Johnston, Miss Catherine Helen "Carrie"  female   NaN
889                              Behr, Mr. Karl Howell    male  26.0
890                                Dooley, Mr. Patrick    male  32.0

[891 rows x 3 columns]

In [ ]:
# 4. Select a rectangular section (subset of rows and columns).
df.loc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [148]:
# Step 4
df.head(5)[['Name','Sex','Age']]

                                                Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                              Heikkinen, Miss Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0

### Part 3: Filtering ###

1. Show only the rows where the age is above 60.

2. Show rows where the fare is above 100 and the passenger was in 1st class.

3. Identify and isolate rows with missing values in the age column.

In [ ]:
#1. Show only the rows where the age is above 60.
df.loc[df['Age'] >= 60]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
275,276,1,1,"Andrews, Miss Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [ ]:
#2. Show rows where the fare is above 100 and the passenger was in 1st class.
df.loc[(df['Fare'] > 100) & (df['Pclass'] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_EUR,CharPerName,FareAgeDiff,AgeGroup
27,28,0,1,"Fortune, Mr. Charles Alexander",0,18.00,3,2,19950,263.0000,C23 C25 C27,S,241.960000,30,245.0000,adult
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",1,NaN,1,0,PC 17569,146.5208,B78,C,134.799136,46,NaN,senior
88,89,1,1,"Fortune, Miss Mabel Helen",1,22.00,3,2,19950,263.0000,C23 C25 C27,S,241.960000,25,241.0000,adult
118,119,0,1,"Baxter, Mr. Quigg Edmond",0,23.00,0,1,PC 17558,247.5208,B58 B60,C,227.719136,24,224.5208,adult
195,196,1,1,"Lurette, Miss Elise",1,57.00,0,0,PC 17569,146.5208,B80,C,134.799136,19,89.5208,adult
215,216,1,1,"Newell, Miss Madeleine",1,30.00,1,0,35273,113.2750,D36,C,104.213000,22,83.2750,adult
258,259,1,1,"Ward, Miss Anna",1,34.00,0,0,PC 17755,512.3292,NaN,C,471.342864,15,478.3292,adult
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",1,57.00,0,1,PC 17582,153.4625,C125,S,141.185500,45,96.4625,adult
269,270,1,1,"Bissette, Miss Amelia",1,34.00,0,0,PC 17760,135.6333,C99,S,124.782636,21,101.6333,adult
297,298,0,1,"Allison, Miss Helen Loraine",1,1.00,1,2,113781,151.5500,C22 C26,S,139.426000,27,150.5500,child
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",1,49.00,0,1,PC 17558,247.5208,B58 B60,C,227.719136,47,198.5208,adult
305,306,1,1,"Allison, Master Hudson Trevor",0,-0.08,1,2,113781,151.5500,C22 C26,S,139.426000,29,151.6300,child
306,307,1,1,"Fleming, Miss Margaret",1,NaN,0,0,17421,110.8833,NaN,C,102.012636,22,NaN,senior
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",1,16.00,1,0,PC 17758,108.9000,C65,C,100.188000,82,92.9000,child
311,312,1,1,"Ryerson, Miss Emily Borie",1,17.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,241.385000,25,245.3750,child
318,319,1,1,"Wick, Miss Mary Natalie",1,30.00,0,2,36928,164.8667,C7,S,151.677364,23,134.8667,adult
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",1,39.00,1,1,16966,134.5000,E34,C,123.740000,56,95.5000,adult
325,326,1,1,"Young, Miss Marie Grice",1,35.00,0,0,PC 17760,135.6333,C32,C,124.782636,23,100.6333,adult
332,333,0,1,"Graham, Mr. George Edward",0,37.00,0,1,PC 17582,153.4625,C91,S,141.185500,25,116.4625,adult
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",1,NaN,1,0,PC 17611,133.6500,NaN,S,122.958000,50,NaN,senior
337,338,1,1,"Burns, Miss Elizabeth Margaret",1,40.00,0,0,16966,134.5000,E40,C,123.740000,30,94.5000,adult
341,342,1,1,"Fortune, Miss Alice Elizabeth",1,23.00,3,2,19950,263.0000,C23 C25 C27,S,241.960000,29,240.0000,adult
373,374,0,1,"Ringhini, Mr. Sante",0,21.00,0,0,PC 17760,135.6333,NaN,C,124.782636,19,114.6333,adult
377,378,0,1,"Widener, Mr. Harry Elkins",0,26.00,0,2,113503,211.5000,C82,C,194.580000,25,185.5000,adult
380,381,1,1,"Bidois, Miss Rosalie",1,41.00,0,0,PC 17757,227.5250,NaN,C,209.323000,20,186.5250,adult
390,391,1,1,"Carter, Mr. William Ernest",0,35.00,1,2,113760,120.0000,B96 B98,S,110.400000,26,85.0000,adult
393,394,1,1,"Newell, Miss Marjorie",1,22.00,1,0,35273,113.2750,D36,C,104.213000,21,91.2750,adult
435,436,1,1,"Carter, Miss Lucile Polk",1,13.00,1,2,113760,120.0000,B96 B98,S,110.400000,24,107.0000,child
438,439,0,1,"Fortune, Mr. Mark",0,63.00,1,4,19950,263.0000,C23 C25 C27,S,241.960000,17,200.0000,adult
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,24.00,1,2,113781,151.5500,C22 C26,S,139.426000,47,127.5500,adult
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",0,17.00,1,0,PC 17758,108.9000,C65,C,100.188000,42,91.9000,child
527,528,0,1,"Farthing, Mr. John",0,NaN,0,0,PC 17483,221.7792,C95,S,204.036864,18,NaN,senior
537,538,1,1,"LeRoy, Miss Bertha",1,29.00,0,0,PC 17761,106.4250,NaN,C,97.911000,18,77.4250,adult
544,545,0,1,"Douglas, Mr. Walter Donald",0,49.00,1,0,PC 17761,106.4250,C86,C,97.911000,26,57.4250,adult
550,551,1,1,"Thayer, Mr. John Borland Jr",0,16.00,0,2,17421,110.8833,C70,C,102.012636,27,94.8833,child
557,558,0,1,"Robbins, Mr. Victor",0,NaN,0,0,PC 17757,227.5250,NaN,C,209.323000,19,NaN,senior
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",1,38.00,1,1,17421,110.8833,C68,C,102.012636,52,72.8833,adult
609,610,1,1,"Shutes, Miss Elizabeth W",1,39.00,0,0,PC 17582,153.4625,C125,S,141.185500,24,114.4625,adult
659,660,0,1,"Newell, Mr. Arthur Webster",0,57.00,0,2,35273,113.2750,D48,C,104.213000,26,56.2750,adult
660,661,1,1,"Frauenthal, Dr. Henry William",0,49.00,2,0,PC 17611,133.6500,NaN,S,122.958000,29,84.6500,adult
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",0,35.00,0,1,PC 17755,512.3292,B51 B53 B55,C,471.342864,34,477.3292,adult
689,690,1,1,"Madill, Miss Georgette Alexandra",1,14.00,0,1,24160,211.3375,B5,S,194.430500,32,197.3375,child
698,699,0,1,"Thayer, Mr. John Borland",0,48.00,1,1,17421,110.8833,C68,C,102.012636,24,62.8833,adult
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",1,17.00,1,0,PC 17757,227.5250,C62 C64,C,209.323000,49,210.5250,child
708,709,1,1,"Cleaver, Miss Alice",1,21.00,0,0,113781,151.5500,NaN,S,139.426000,19,130.5500,adult
716,717,1,1,"Endres, Miss Caroline Louise",1,37.00,0,0,PC 17757,227.5250,C45,C,209.323000,28,190.5250,adult
730,731,1,1,"Allen, Miss Elisabeth Walton",1,28.00,0,0,24160,211.3375,B5,S,194.430500,28,183.3375,adult
737,738,1,1,"Lesurer, Mr. Gustave J",0,34.00,0,0,PC 17755,512.3292,B101,C,471.342864,22,478.3292,adult
742,743,1,1,"Ryerson, Miss Susan Parker ""Suzette""",1,20.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,241.385000,36,242.3750,adult
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",1,35.00,1,2,113760,120.0000,B96 B98,S,110.400000,41,85.0000,adult
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",1,42.00,0,1,24160,211.3375,B3,S,194.430500,53,169.3375,adult
802,803,1,1,"Carter, Master William Thornton II",0,10.00,1,2,113760,120.0000,B96 B98,S,110.400000,34,110.0000,child
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",1,44.00,1,1,36928,164.8667,NaN,S,151.677364,42,120.8667,adult

In [151]:
#3. Identify and isolate rows with missing values in the age column.
df.loc[df['Age'].isna()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

### Part 4: Reindexing and Dropping ###

1. Reverse the row order of the dataset.

2. Remove one column from the dataset.

3. Remove all rows with missing values in the age column.

In [152]:
#1. Reverse the row order of the dataset.
df.iloc[::-1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

In [153]:
#2. Remove one column from the dataset.
df.drop(index=0)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [154]:
#3. Remove all rows with missing values in the age column.
df.dropna(subset=['Age'])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Part 5: Arithmetic and Data Alignment ###

1. Create a new column that converts fares from USD to Euros.

2. Subtract the average age from every age value.

3. Subtract a custom array from two selected columns in the dataset.

In [ ]:
#1. Create a new column that converts fares from USD to Euros.
df['Fare_EUR'] = df['Fare'] * 0.92
display(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_EUR,CharPerName,FareAgeDiff,AgeGroup
0,1,0,3,"Braund, Mr. Owen Harris",0,21.0,1,0,A/5 21171,7.2500,NaN,S,6.670000,23,-13.7500,adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,37.0,1,0,PC 17599,71.2833,C85,C,65.580636,51,34.2833,adult
2,3,1,3,"Heikkinen, Miss Laina",1,25.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7.291000,21,-17.0750,adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,34.0,1,0,113803,53.1000,C123,S,48.852000,44,19.1000,adult
4,5,0,3,"Allen, Mr. William Henry",0,34.0,0,0,373450,8.0500,NaN,S,7.406000,24,-25.9500,adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,26.0,0,0,211536,13.0000,NaN,S,11.960000,21,-13.0000,adult
887,888,1,1,"Graham, Miss Margaret Edith",1,18.0,0,0,112053,30.0000,B42,S,27.600000,27,12.0000,adult
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",1,NaN,1,2,W./C. 6607,23.4500,NaN,S,21.574000,39,NaN,senior
889,890,1,1,"Behr, Mr. Karl Howell",0,25.0,0,0,111369,30.0000,C148,C,27.600000,21,5.0000,adult
890,891,0,3,"Dooley, Mr. Patrick",0,31.0,0,0,370376,7.7500,NaN,Q,7.130000,19,-23.2500,adult

In [156]:
#2. Subtract the average age from every age value.
df['Age'] = df['Age'] - 1
display(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_EUR
0,1,0,3,"Braund, Mr. Owen Harris",male,21.0,1,0,A/5 21171,7.2500,NaN,S,6.670000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,37.0,1,0,PC 17599,71.2833,C85,C,65.580636
2,3,1,3,"Heikkinen, Miss Laina",female,25.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7.291000
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,34.0,1,0,113803,53.1000,C123,S,48.852000
4,5,0,3,"Allen, Mr. William Henry",male,34.0,0,0,373450,8.0500,NaN,S,7.406000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,26.0,0,0,211536,13.0000,NaN,S,11.960000
887,888,1,1,"Graham, Miss Margaret Edith",female,18.0,0,0,112053,30.0000,B42,S,27.600000
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,21.574000
889,890,1,1,"Behr, Mr. Karl Howell",male,25.0,0,0,111369,30.0000,C148,C,27.600000
890,891,0,3,"Dooley, Mr. Patrick",male,31.0,0,0,370376,7.7500,NaN,Q,7.130000

In [157]:
#3. Subtract a custom array from two selected columns in the dataset.
arr = np.array([10, 5])
df[['Age', 'Fare']] - arr

      Age     Fare
0    11.0   2.2500
1    27.0  66.2833
2    15.0   2.9250
3    24.0  48.1000
4    24.0   3.0500
..    ...      ...
886  16.0   8.0000
887   8.0  25.0000
888   NaN  18.4500
889  15.0  25.0000
890  21.0   2.7500

[891 rows x 2 columns]

### Part 6: Applying Functions ###

1. Create a new column with the number of characters in each name.

2. Calculate the difference between fare and age for each row.

3. Round all numerical values in the dataset to one decimal place.

**Notes**

Step 1

- This function assumes that spaces and symbols are included in the chracter count

In [ ]:
#1. Create a new column with the number of characters in each name.

df['CharPerName'] = df['Name'].str.strip().str.len()
display(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_EUR,CharPerName,FareAgeDiff,AgeGroup
0,1,0,3,"Braund, Mr. Owen Harris",0,21.0,1,0,A/5 21171,7.2500,NaN,S,6.670000,23,-13.7500,adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,37.0,1,0,PC 17599,71.2833,C85,C,65.580636,51,34.2833,adult
2,3,1,3,"Heikkinen, Miss Laina",1,25.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7.291000,21,-17.0750,adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,34.0,1,0,113803,53.1000,C123,S,48.852000,44,19.1000,adult
4,5,0,3,"Allen, Mr. William Henry",0,34.0,0,0,373450,8.0500,NaN,S,7.406000,24,-25.9500,adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,26.0,0,0,211536,13.0000,NaN,S,11.960000,21,-13.0000,adult
887,888,1,1,"Graham, Miss Margaret Edith",1,18.0,0,0,112053,30.0000,B42,S,27.600000,27,12.0000,adult
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",1,NaN,1,2,W./C. 6607,23.4500,NaN,S,21.574000,39,NaN,senior
889,890,1,1,"Behr, Mr. Karl Howell",0,25.0,0,0,111369,30.0000,C148,C,27.600000,21,5.0000,adult
890,891,0,3,"Dooley, Mr. Patrick",0,31.0,0,0,370376,7.7500,NaN,Q,7.130000,19,-23.2500,adult

In [176]:
#2. Calculate the difference between fare and age for each row.
df['FareAgeDiff'] = df['Fare'].sub(df['Age'])

In [177]:
#3. Round all numerical values in the dataset to one decimal place.
df.round(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_EUR,CharPerName,FareAgeDiff,AgeGroup
0,1,0,3,"Braund, Mr. Owen Harris",0,21.0,1,0,A/5 21171,7.2,NaN,S,6.7,23,-13.8,adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,37.0,1,0,PC 17599,71.3,C85,C,65.6,51,34.3,adult
2,3,1,3,"Heikkinen, Miss Laina",1,25.0,0,0,STON/O2. 3101282,7.9,NaN,S,7.3,21,-17.1,adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,34.0,1,0,113803,53.1,C123,S,48.9,44,19.1,adult
4,5,0,3,"Allen, Mr. William Henry",0,34.0,0,0,373450,8.0,NaN,S,7.4,24,-26.0,adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,26.0,0,0,211536,13.0,NaN,S,12.0,21,-13.0,adult
887,888,1,1,"Graham, Miss Margaret Edith",1,18.0,0,0,112053,30.0,B42,S,27.6,27,12.0,adult
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",1,NaN,1,2,W./C. 6607,23.4,NaN,S,21.6,39,NaN,senior
889,890,1,1,"Behr, Mr. Karl Howell",0,25.0,0,0,111369,30.0,C148,C,27.6,21,5.0,adult
890,891,0,3,"Dooley, Mr. Patrick",0,31.0,0,0,370376,7.8,NaN,Q,7.1,19,-23.2,adult

### Part 7: Mapping and Transformation ###
1. Convert categorical values in the gender column to numeric codes.

2. Create a new column that categorizes age into groups (e.g., child, adult, senior).

**Notes**

Step 2

- This function assumes that the a child becomes an adult at 18 , adult becomes a senior at 65

In [161]:
#1. Convert categorical values in the gender column to numeric codes.
df['Sex'] = df['Sex'].map(lambda x: 0 if x == 'male' else 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                #2. Create a new column that categorizes age into groups (e.g., child, adult, senior).
                                                                                                                 
display(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_EUR,CharPerName,FareAgeDiff
0,1,0,3,"Braund, Mr. Owen Harris",0,21.0,1,0,A/5 21171,7.2500,NaN,S,6.670000,23,-13.7500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,37.0,1,0,PC 17599,71.2833,C85,C,65.580636,51,34.2833
2,3,1,3,"Heikkinen, Miss Laina",1,25.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7.291000,21,-17.0750
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,34.0,1,0,113803,53.1000,C123,S,48.852000,44,19.1000
4,5,0,3,"Allen, Mr. William Henry",0,34.0,0,0,373450,8.0500,NaN,S,7.406000,24,-25.9500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,26.0,0,0,211536,13.0000,NaN,S,11.960000,21,-13.0000
887,888,1,1,"Graham, Miss Margaret Edith",1,18.0,0,0,112053,30.0000,B42,S,27.600000,27,12.0000
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",1,NaN,1,2,W./C. 6607,23.4500,NaN,S,21.574000,39,NaN
889,890,1,1,"Behr, Mr. Karl Howell",0,25.0,0,0,111369,30.0000,C148,C,27.600000,21,5.0000
890,891,0,3,"Dooley, Mr. Patrick",0,31.0,0,0,370376,7.7500,NaN,Q,7.130000,19,-23.2500

In [162]:
#2. Create a new column that categorizes age into groups (e.g., child, adult, senior).

def categorize_age(x):
    if x < 18:
        return 'child'
    elif x < 65:
        return 'adult'
    else:
        return 'senior'

df['AgeGroup'] = df['Age'].map(categorize_age)
display(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_EUR,CharPerName,FareAgeDiff,AgeGroup
0,1,0,3,"Braund, Mr. Owen Harris",0,21.0,1,0,A/5 21171,7.2500,NaN,S,6.670000,23,-13.7500,adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,37.0,1,0,PC 17599,71.2833,C85,C,65.580636,51,34.2833,adult
2,3,1,3,"Heikkinen, Miss Laina",1,25.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7.291000,21,-17.0750,adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,34.0,1,0,113803,53.1000,C123,S,48.852000,44,19.1000,adult
4,5,0,3,"Allen, Mr. William Henry",0,34.0,0,0,373450,8.0500,NaN,S,7.406000,24,-25.9500,adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,26.0,0,0,211536,13.0000,NaN,S,11.960000,21,-13.0000,adult
887,888,1,1,"Graham, Miss Margaret Edith",1,18.0,0,0,112053,30.0000,B42,S,27.600000,27,12.0000,adult
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",1,NaN,1,2,W./C. 6607,23.4500,NaN,S,21.574000,39,NaN,senior
889,890,1,1,"Behr, Mr. Karl Howell",0,25.0,0,0,111369,30.0000,C148,C,27.600000,21,5.0000,adult
890,891,0,3,"Dooley, Mr. Patrick",0,31.0,0,0,370376,7.7500,NaN,Q,7.130000,19,-23.2500,adult

### Part 8: Pure Python ###
Freely choose one task from each of Parts 2, 3, or 5 (3 tasks in total). Try to solve that chosen task without using Pandas, only with pure Python code. For this, convert the CSV dataset into a list (or any other native Python data type) and implement the task without using any external libraries. Then, compare the execution time of both versions (with Pandas and without it).

In [163]:
# Read + Convert csv to list of dictionaries
import csv
import urllib.request

url = "https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv"

with urllib.request.urlopen(url) as response:
    lines = [line.decode('utf-8') for line in response]

reader = csv.DictReader(lines)
records = list(reader)

In [164]:
# Part 2-1. Select the names column.
names = [row['Name'] for row in records]
# display(names)

In [165]:
# Part 3-1. Rows where age is above 60.
above_60 = [row for row in records if row['Age'] != '' and float(row['Age']) > 60]
# display(above_60)

In [166]:
# Part 5-1. Convert Fare to Euros.
fare_eur = [float(row['Fare']) * 0.92 for row in records]
# display(fare_eur)

**Part 2 Step 1 Comparison**

In [ ]:
print('Pandas Time')
%timeit df['Name'].tolist()

print('\nPure Python Time')
%timeit [row['Name'] for row in records]

Pandas Time
3.36 μs ± 40.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

Pure Python Time
23.7 μs ± 771 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

**Part 3 Step 1 Comparison**

Note: switched used .values for faster compuation

In [170]:
print('Pandas Time')
%timeit df[df['Age'].values > 60]

print('\nPure Python Time')
%timeit [row for row in records if row['Age'] != '' and float(row['Age']) > 60]

Pandas Time
64.8 μs ± 637 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

Pure Python Time
73.4 μs ± 806 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

**Part 5 Step 1 Comparison**

Note: switched used .values for faster compuation

In [171]:
print('Pandas Time')
%timeit df['Fare'].values * 0.92

print('\nPure Python Time')
%timeit [float(row['Fare']) * 0.92 for row in records]

Pandas Time
2.27 μs ± 21.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

Pure Python Time
72.4 μs ± 744 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

**Conclusion**

Pandas was often considerably faster than using pure python